### ISSUE TITLE
Add Ping-o-Matic

### ISSUE THREAD

**Issue by tankerkiller125** [gaaarfild/laravel-pinger#1]
It would be awesome to add http://pingomatic.com to the list of sites. (Plus is may speed up development to add other services)

**Comment by garf** [comment]
I have not found the URL to send weblog pings. Do you have such URL?

**Comment by tankerkiller125** [comment]
It looks a little somthing like this (example to my own blog pinging all
the sites possible) [Here](http://pingomatic.com/ping/?title=Tankerkiller125%27s+Blog&blogurl=http%3A%2F%2Ftankerkiller125.ml&rssurl=http%3A%2F%2F&chk_weblogscom=on&chk_blogs=on&chk_feedburner=on&chk_newsgator=on&chk_myyahoo=on&chk_pubsubcom=on&chk_blogdigger=on&chk_weblogalot=on&chk_newsisfree=on&chk_topicexchange=on&chk_google=on&chk_tailrank=on&chk_skygrid=on&chk_collecta=on&chk_superfeedr=on)

**Comment by garf** [comment]
Thank you. I will add this soon.
