### ISSUE TITLE
pingAll function

### ISSUE THREAD

**Issue by angelocala94** [gaaarfild/laravel-pinger#9]
Why the pingAll function takes the urls from the configuration file, instead of calling every other single function?
Right now the pingAll method does not pings on PingOMatic?

**Comment by garf** [comment]
Good notice. Thank you. I will fix it in the next release.

**Comment by angelocala94** [comment]
Thank you for this package, have a good day!

**Comment by garf** [comment]
@angelocala94 i've made changes.. Please update.
Currently I just added pingomatic manually, because it has different logic than other services.
TODO: refactor them in proper way in the future.
Thank you again for your feedback.

**Comment by angelocala94** [comment]
Many thanks!
